pipeline {
    agent any

    tools {
        // Ensure this matches the exact name of your JDK installation in Jenkins
        jdk 'openjdk-jdk8u422'
    }

    stages {
    
    	stage('Example'){
    		steps{
		 sh '''
		   env | grep -e PATH -e JAVA_HOME
		   which java
		   java -version
		 '''    		
    		}
    	}
    
        stage('Setup') {
            steps {
                // Verify Java installation
                sh 'java -version'
                // Verify Maven installation
                sh 'mvn -version'
            }
        }
        stage('Build') {
            steps {
                // Run a Maven build to check everything is set up correctly
                sh 'mvn clean install'
            }
        }
    }
}

