pipeline {
    agent any

    tools {
        // Replace 'java-8-openjdk-amd64' with the name of your JDK in Jenkins
        jdk 'java-8-openjdk-amd64'
    }

    stages {
        stage('Setup') {
            steps {
                // Verify Java installation
                sh 'java -version'
                // Verify Maven installation
                sh 'mvn -version'
            }
        }
        stage('Build') {
            steps {
                // Run a Maven build to check everything is set up correctly
                sh 'mvn clean install'
            }
        }
    }
}

